nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.9.1.cjs

npmScopes:
  tiptap-pro:
    npmRegistryServer: "https://registry.tiptap.dev/"
    npmAuthToken: "RrlgDIkIRQnhfiZPPepeUTkdbsPIfhoKW4FHfdKswVf+jWeTz1wElfZkAK/kGgbE"


packageExtensions:
  "@primeuix/themes@*":
    dependencies:
      "@primeuix/styles": "*"
  vue-tsc@*:
    dependencies:
      typescript: "*"