
const KANBAN_TYPE_KANBAN = 'kanban'
const KANBAN_TYPE_EPIC = 'epic'
const KANBAN_TYPE_WORK = 'work'
const KANBAN_TYPES = [KANBAN_TYPE_KANBAN, KANBAN_TYPE_EPIC, KANBAN_TYPE_WORK]

export {
    KANBAN_TYPE_KANBAN,
    KANBAN_TYPE_EPIC,
    KANBAN_TYPE_WORK,
    KANBAN_TYPES
}